pluginManagement {
    def offlineRepoPath = providers.gradleProperty('mlog.offlineRepo').orNull

    includeBuild 'build-logic'

    repositories {
        if (offlineRepoPath != null && !offlineRepoPath.isBlank()) {
            maven { url = uri(offlineRepoPath) }
        } else {
            gradlePluginPortal()
            mavenCentral()
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    def offlineRepoPath = providers.gradleProperty('mlog.offlineRepo').orNull

    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        if (offlineRepoPath != null && !offlineRepoPath.isBlank()) {
            maven { url = uri(offlineRepoPath) }
        } else {
            mavenCentral()
        }
    }
}

rootProject.name = 'mundane-logger'
include ':modules:mundane-logger-bom'
include ':modules:api'
include ':modules:core'
include ':modules:slf4j'
include ':modules:testkit'
include ':modules:architecture-tests'
include ':modules:native-tests'
