plugins {
    id 'mlog.platform-conventions'
}

description = 'Dependency alignment BOM for mundane logger.'

dependencies {
    constraints {
        api project(':modules:api')
        api project(':modules:core')
        api project(':modules:slf4j')
        api project(':modules:testkit')
    }
}

publishing {
    publications {
        mavenBom(MavenPublication) {
            artifactId = 'mundane-logger-bom'
        }
    }
}
